#ifndef _SOFTWARE_VERSION_H_
#define _SOFTWARE_VERSION_H_

#define SOFTWARE_VERSION_MAJOR          0
#define SOFTWARE_VERSION_MINOR          1
#define SOFTWARE_VERSION_PATCH          0

#define SOFTWARE_UPDATE_DATE_DAY        14
#define SOFTWARE_UPDATE_DATE_MONTH      05
#define SOFTWARE_UPDATE_DATE_YEAR       23

#endif /* _SOFTWARE_VERSION_H_ */