#ifndef _SOFTWARE_VERSION_H_
#define _SOFTWARE_VERSION_H_

#define SOFTWARE_VERSION_MAJOR          0
#define SOFTWARE_VERSION_MINOR          3
#define SOFTWARE_VERSION_PATCH          4

#define SOFTWARE_UPDATE_DATE_DAY        20
#define SOFTWARE_UPDATE_DATE_MONTH      06
#define SOFTWARE_UPDATE_DATE_YEAR       23

#endif /* _SOFTWARE_VERSION_H_ */